openapi: 3.0.1
info:
  title: User Location API
  description: Manages and retrieves location data for users. Operations to create user-specific locations and querying for the most recent location for a specific user, all known locations for a specific user and most recent locations for all users.
  version: v1
paths:
  /api/UserLocations:
    post:
      tags:
        - UserLocations
      summary: Creates a new User Location
      requestBody:
        description: The request needed to create a new User Location.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserLocationRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateUserLocationRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateUserLocationRequest'
      responses:
        '200':
          description: Returns if the User Location is successfully created.
        '400':
          description: Returns if the request contains validation errors.
  /api/UserLocations/{userId}/recent:
    get:
      tags:
        - UserLocations
      summary: Gets the most recent user location by User Id.
      parameters:
        - name: userId
          in: path
          description: The Id of the user.
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Returns if the retrival of the users location is successful.
        '400':
          description: Returns if there's a validation error with the request.
        '404':
          description: Returns if there is no data to retrive.
  /api/UserLocations/{userId}:
    get:
      tags:
        - UserLocations
      summary: Gets All of the users known locations by User Id.
      parameters:
        - name: userId
          in: path
          description: The Id of the user.
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Returns if the retrival of the users locations is successful.
        '400':
          description: Returns if there's a validation error with the request.
        '404':
          description: Returns if there is no data to retrive.
  /api/UserLocations/recent:
    get:
      tags:
        - UserLocations
      summary: Gets all users most recent locations.
      responses:
        '200':
          description: Returns if the retrival of the user locations is successful.
        '404':
          description: Returns there is no data to retrive.
components:
  schemas:
    CreateUserLocationRequest:
      type: object
      properties:
        userId:
          type: integer
          description: The Id of the user.
          format: int32
        latitude:
          type: number
          description: The latitude of the location.
          format: double
        longitude:
          type: number
          description: The longitude of the location.
          format: double
      additionalProperties: false
      description: The request to create a new user location.